- name: Install az
  hosts: all
  gather_facts: true
  become: true
  become_method: sudo
  vars:
    package_names:
      - az-cli

  tasks:
  - name: "Check if listed package is installed or not on Centos Linux family"
    command: az --version
    loop: "{{ package_names }}"
    register: package_check
    when: ansible_facts['os_family'] == "Centos"

  - name: "Print execution results"
    debug:
      msg: "Package is installed"
    when: package_check is succeeded

  # - name: push az  package to remote host
  #   copy:
  #    src: azure-cli-2.0.80-1.el7.x86_64.rpm
  #    dest: /opt/azure-cli-2.0.80-1.el7.x86_64.rpm
  #    owner: root
  #    group: root
  #    mode: '0744'

  - name: download sources
    get_url: url=https://packages.microsoft.com/yumrepos/azure-cli/azure-cli-2.0.80-1.el7.x86_64.rpm dest=/opt/
    loop: "{{ package_names }}"
    when: package_check is failed and ansible_facts['os_family'] == "Centos"



  - name: install az
    yum: name=/opt/azure-cli-2.0.80-1.el7.x86_64.rpm state=present
    loop: "{{ package_names }}"
    when: package_check is failed and ansible_facts['os_family'] == "Centos"
