- name: Install az
  hosts: all
  gather_facts: true
  become: true
  become_method: sudo 

  tasks:

  - name: download sources
    get_url: url=https://packages.microsoft.com/yumrepos/azure-cli/azure-cli-2.0.80-1.el7.x86_64.rpm dest=/opt/
    

  # - name: push az  package to remote host
  #   copy:
  #    src: azure-cli-2.0.80-1.el7.x86_64.rpm
  #    dest: /opt/azure-cli-2.0.80-1.el7.x86_64.rpm
  #    owner: root
  #    group: root
  #    mode: '0744'

  - name: install az 
    yum: name=/opt/azure-cli-2.0.80-1.el7.x86_64.rpm state=present
